import { describe, it, expect } from "vitest";
import { EMPLOYEES, FLIGHTS, CONFIG, DAYS_WITH_DATA, CURRENT_WEEK_START, CURRENT_WEEK_LABEL } from "../lib/seed-data";
// (CURRENT_WEEK_START above is also used for the real-plan-based invariant
// checks in this file, in addition to the synthetic TEST_WEEK_START below.)
import { buildDraftPlanBundle, planIdForWeek } from "../lib/planning/weekly-plan-service";
import { isFlexibleGeneralPool, isGenerationDrivenPopulation } from "../lib/planning/workforce-pools";
import { checkRestBetweenDays, auditStaticShiftRestFeasibility } from "../lib/planning/validation";
import { enforceRestInvariantAcrossWeek, GeneratedShiftAssignment, PriorDayShiftMap } from "../lib/planning/shift-generation";
import { Employee, WeeklyShiftEntry } from "../lib/types";
import { getShiftTimesAs } from "../lib/shift-templates";
import { restHoursBetween } from "../lib/roster-generation";
import { flightDateFor } from "../lib/flight-date";

// A Monday well before the 2026-09-20 GMT+1 -> GMT regime change, used for
// the synthetic enforceRestInvariantAcrossWeek unit tests below (whose
// hardcoded shift-time expectations, e.g. JR01 05:45-18:15, are written
// against the OLD (PRE_2026_09_20) regime -- see lib/shift-templates.ts).
const TEST_WEEK_START = "2026-01-05";

/**
 * HARD invariants, not reporting assertions -- these must never fail
 * against the real demo plan. Added after a real production bug report:
 * a persisted Agent Schedule showed an employee (Abderrahim Benali) with
 * consecutive JR01 shifts (05:45-18:15 back to back), which is only
 * 11.5h of real rest -- below the confirmed 15h minimum. Root cause:
 * that specific persisted plan predated this session's Stage 6 fixes (it
 * was generated by an older build where this employee's static baseline
 * passed straight through unmodified -- see the delivered incident
 * report for the full trace). This file locks in two independent layers
 * so the same failure mode can never silently return:
 *  1. enforceRestInvariantAcrossWeek (shift-generation.ts) -- a whole-week
 *     safety net that re-walks Stage 6's real output and hard-drops any
 *     shift that would violate 15h rest against that employee's true
 *     last-worked shift, independent of and in addition to the existing
 *     per-day eligibility gate inside generateFlexiblePoolShifts.
 *  2. This test file -- a HARD, non-reporting whole-plan check against
 *     the actual buildDraftPlanBundle output (the same function every
 *     API route uses), so a regression fails CI, not just a manual audit.
 */
function rebuildEmployeeFromRoster(
  employee: Employee,
  rosterByKey: Map<string, { status: "working" | "off"; shift_code: string | null }>
): Employee {
  const weekly_shifts: WeeklyShiftEntry[] = DAYS_WITH_DATA.map((day) => {
    const entry = rosterByKey.get(`${employee.id}|${day}`);
    return { day_of_week: day, status: entry?.status ?? "off", shift_code: entry?.shift_code ?? null };
  });
  return { ...employee, weekly_shifts };
}

describe("HARD invariant: zero 15h rest violations in the real generated/persisted-shape plan", () => {
  const planId = planIdForWeek(CURRENT_WEEK_START);
  const bundle = buildDraftPlanBundle({
    planId,
    weekStart: CURRENT_WEEK_START,
    weekLabel: CURRENT_WEEK_LABEL,
    revision: 1,
    flights: FLIGHTS,
    employees: EMPLOYEES,
    config: CONFIG,
    daysOrder: DAYS_WITH_DATA,
  });

  const rosterByKey = new Map(
    bundle.rosterEntries.map((r) => [`${r.employee_id}|${r.day_of_week}`, { status: r.status, shift_code: r.shift_code }])
  );

  it("HARD GATE: every flexible General T1 employee's real persisted-shape week has ZERO rest-between-days issues -- including the confirmed 15h minimum, overnight shifts, and the cyclic Sunday -> following-Monday transition", () => {
    const flexibleEmployees = EMPLOYEES.filter(isFlexibleGeneralPool);
    const violators: string[] = [];

    for (const employee of flexibleEmployees) {
      const rebuilt = rebuildEmployeeFromRoster(employee, rosterByKey);
      const issues = checkRestBetweenDays(rebuilt, DAYS_WITH_DATA, CONFIG, CURRENT_WEEK_START);
      for (const issue of issues) {
        violators.push(`${employee.name} (${employee.id}): ${issue.description}`);
      }
    }

    // HARD gate -- not a reporting count. Any violation here means the
    // safety net (enforceRestInvariantAcrossWeek) failed to catch
    // something the per-day gate also missed.
    expect(violators, violators.join("\n")).toHaveLength(0);
  });

  it("HARD GATE: no consecutive pair of WORKING roster entries for a FLEXIBLE General T1 employee, same displayed week, falls below 15h of real elapsed rest -- computed directly from persisted WeeklyPlanRosterEntry rows (day_of_week + shift_code), the exact data the Agent Schedule UI renders, not a re-derived employee object. Scoped to the flexible pool: Stage 6 (this task's scope) is the only population whose day-by-day placement is decided by generation at all -- a non-flexible employee's own static/foreign-company baseline pattern is a separate, pre-existing workforce-design question, already tracked (never silently) by auditStaticShiftRestFeasibility below, not something Stage 6 generation could ever have caused or can fix by itself without rewriting a specialized team's own fixed model, which is explicitly out of scope (see the delivered report)", () => {
    const violators: string[] = [];
    const flexibleIds = new Set(EMPLOYEES.filter(isFlexibleGeneralPool).map((e) => e.id));

    for (const employee of EMPLOYEES) {
      if (!flexibleIds.has(employee.id)) continue;
      const entries = DAYS_WITH_DATA.map((d) => rosterByKey.get(`${employee.id}|${d}`)).filter(
        (e): e is { status: "working" | "off"; shift_code: string | null } => !!e
      );
      // Only consecutive-day (index N, N+1) pairs within the displayed week.
      for (let i = 0; i < entries.length - 1; i++) {
        const today = entries[i];
        const tomorrow = entries[i + 1];
        if (today.status !== "working" || tomorrow.status !== "working") continue;
        if (!today.shift_code || !tomorrow.shift_code) continue;

        const todayTimes = getShiftTimesAs(today.shift_code, flightDateFor(CURRENT_WEEK_START, DAYS_WITH_DATA[i]));
        const tomorrowTimes = getShiftTimesAs(tomorrow.shift_code, flightDateFor(CURRENT_WEEK_START, DAYS_WITH_DATA[i + 1]));
        const rest = restHoursBetween(todayTimes.shift_start, todayTimes.shift_end, tomorrowTimes.shift_start);
        if (rest < CONFIG.minimum_rest_hours) {
          violators.push(
            `${employee.name} (${employee.id}): ${DAYS_WITH_DATA[i]} ${today.shift_code} -> ${DAYS_WITH_DATA[i + 1]} ${tomorrow.shift_code}: only ${rest}h rest`
          );
        }
      }
    }

    expect(violators, violators.join("\n")).toHaveLength(0);
  });

  it("whole-demo finding: non-flexible (static/foreign-company/fixed-team) employees' OWN pre-existing rest feasibility is real, pre-existing workforce-design data unrelated to Stage 6, and is already reported (never hidden) via auditStaticShiftRestFeasibility -- proves that population isn't simply unchecked", () => {
    const restCapacityIssues = auditStaticShiftRestFeasibility(EMPLOYEES, isFlexibleGeneralPool, CONFIG, CURRENT_WEEK_START);
    expect(Array.isArray(restCapacityIssues)).toBe(true);
    expect(restCapacityIssues.length).toBeGreaterThan(0); // the demo dataset genuinely has some -- confirmed reported, not silently dropped
  });

  it("HARD GATE, ALL EMPLOYEES (not just the flexible pool): zero consecutive-working-day pairs in the FINAL persisted-shape roster fall below 15h rest -- the confirmed minimum is a hard employee constraint regardless of which planning model (Stage 6 demand-driven, or a specialized/fixed team's own configured rotation) produced the day. A specialized team whose configured rotation cannot itself satisfy 15h has its offending day dropped to OFF and reported as a BLOCKING configuration conflict (see specializedRestConflicts in generate-draft-plan.ts) rather than ever reaching this check as an illegal pair. NOTE: this checks the hard rest_violation type only -- cross_week_continuity_uncertain (the Sunday -> following-Monday wraparound, for demand-driven populations only) is a deliberate, visible, non-blocking WARNING, not a hard violation -- see the next test.", () => {
    const violators: string[] = [];
    for (const employee of EMPLOYEES) {
      const rebuilt = rebuildEmployeeFromRoster(employee, rosterByKey);
      const issues = checkRestBetweenDays(rebuilt, DAYS_WITH_DATA, CONFIG, CURRENT_WEEK_START).filter((i) => i.type === "rest_violation");
      for (const issue of issues) violators.push(`${employee.name} (${employee.assignment}): ${issue.description}`);
    }
    expect(violators, violators.join("\n")).toHaveLength(0);
  });

  it("cross_week_continuity_uncertain fires ONLY for demand-driven populations at the Sunday -> following-Monday wraparound, never rest_violation, and never for a fixed/cyclic team", () => {
    for (const employee of EMPLOYEES) {
      const rebuilt = rebuildEmployeeFromRoster(employee, rosterByKey);
      const issues = checkRestBetweenDays(rebuilt, DAYS_WITH_DATA, CONFIG, CURRENT_WEEK_START);
      const wraparoundIssues = issues.filter((i) => i.dayOfWeek?.includes("following week"));
      for (const issue of wraparoundIssues) {
        if (isGenerationDrivenPopulation(rebuilt)) {
          expect(issue.type, `${employee.name} (${employee.assignment}): ${issue.description}`).toBe("cross_week_continuity_uncertain");
        } else {
          expect(issue.type, `${employee.name} (${employee.assignment}): ${issue.description}`).toBe("rest_violation");
        }
      }
    }
  });

  it("reports the BLOCKING specialized-rest-conflict configuration issues this run actually produced -- a nonzero count here means the demo's own specialized/fixed workforce-design data genuinely cannot satisfy 15h on its own (a real finding to hand to workforce design, not a bug), and confirms the conflict is surfaced, never silently swallowed", () => {
    const blocking = bundle.plan.configuration_issues.filter((c) => c.description.startsWith("BLOCKING:"));
    // Every blocking conflict must name the confirmed minimum and explain
    // the day was left OFF rather than persisting an illegal sequence --
    // never phrased as a mere warning.
    for (const issue of blocking) {
      expect(issue.description).toContain(`${CONFIG.minimum_rest_hours}h minimum`);
      expect(issue.description).toContain("left OFF rather than persisting an illegal sequence");
    }
    expect(blocking.length).toBeGreaterThanOrEqual(0);
  });
});

describe("enforceRestInvariantAcrossWeek — the safety-net mechanism itself, proven against a deliberately violating input", () => {
  it("drops a shift that would give an employee only 11.5h rest (JR01 -> JR01 back to back) against their last REAL kept shift, and correctly re-admits the day after a drop once the real elapsed gap (skipping the dropped day) is genuinely >= 15h -- JR01 every day alternates keep/drop/keep/drop, it does not cascade into dropping the whole rest of the week", () => {
    const days = ["Monday", "Tuesday", "Wednesday", "Thursday"];
    const generatedShiftsByDay: Record<string, GeneratedShiftAssignment[]> = {
      Monday: [{ employeeId: "e1", dayOfWeek: "Monday", shiftCode: "JR01", coversRoles: ["Boarding"] }],
      Tuesday: [{ employeeId: "e1", dayOfWeek: "Tuesday", shiftCode: "JR01", coversRoles: ["Boarding"] }],
      Wednesday: [{ employeeId: "e1", dayOfWeek: "Wednesday", shiftCode: "JR01", coversRoles: ["Boarding"] }],
      Thursday: [{ employeeId: "e1", dayOfWeek: "Thursday", shiftCode: "JR01", coversRoles: ["Boarding"] }],
    };

    const { repaired, dropped } = enforceRestInvariantAcrossWeek(days, generatedShiftsByDay, 15, TEST_WEEK_START);

    expect(repaired.Monday).toHaveLength(1); // first occurrence always kept (nothing before it to violate)
    expect(repaired.Tuesday).toHaveLength(0); // only 11.5h since Monday (1 real day apart) -- dropped
    // Wednesday is 2 REAL calendar days after Monday's last kept shift
    // (Tuesday was dropped, not real) -- 34.5h of genuine rest, correctly
    // kept. A naive "always assume 1 day since the last entry in the
    // loop" implementation would wrongly drop this too (a real bug found
    // and fixed while building this safety net -- restHoursBetween alone
    // always assumes exactly 1 elapsed calendar day, which undercounts
    // rest across any skipped/dropped day; see restHoursBetweenAcrossGap).
    expect(repaired.Wednesday).toHaveLength(1);
    expect(repaired.Thursday).toHaveLength(0); // only 11.5h since Wednesday (1 real day apart) -- dropped again
    expect(dropped).toHaveLength(2);
    expect(dropped.every((d) => d.restHours === 11.5)).toBe(true);
  });

  it("regression: a shift separated from the employee's last REAL shift by exactly one dropped (never-real) day in between is judged on the TRUE elapsed calendar gap, not on a hardcoded 1-day assumption", () => {
    const days = ["Monday", "Tuesday", "Wednesday"];
    // Monday MT01 (05:45-14:45); Tuesday MT01 again -> only 15h flat
    // (borderline pass) is too fragile to prove the gap math, so use a
    // code pair that is UNAMBIGUOUSLY a violation for 1 real day apart
    // but unambiguously fine for 2: JR01 (05:45-18:15) repeated -> 11.5h
    // for a 1-day gap, 35.5h for a 2-day gap.
    const generatedShiftsByDay: Record<string, GeneratedShiftAssignment[]> = {
      Monday: [{ employeeId: "e1", dayOfWeek: "Monday", shiftCode: "JR01", coversRoles: ["Boarding"] }],
      Tuesday: [], // nothing generated Tuesday at all (not even a violating candidate) -- a genuine OFF day
      Wednesday: [{ employeeId: "e1", dayOfWeek: "Wednesday", shiftCode: "JR01", coversRoles: ["Boarding"] }],
    };

    const { repaired, dropped } = enforceRestInvariantAcrossWeek(days, generatedShiftsByDay, 15, TEST_WEEK_START);

    expect(repaired.Monday).toHaveLength(1);
    expect(repaired.Wednesday).toHaveLength(1); // 2 real calendar days after Monday -- ample rest, never dropped
    expect(dropped).toHaveLength(0);
  });

  it("catches a violation spanning the previous week's real boundary shift via priorWeekBoundaryContext, not just violations wholly inside the displayed week", () => {
    const days = ["Monday"];
    const generatedShiftsByDay: Record<string, GeneratedShiftAssignment[]> = {
      Monday: [{ employeeId: "e1", dayOfWeek: "Monday", shiftCode: "JR01", coversRoles: ["Boarding"] }],
    };
    // Previous week's real Sunday: JR01 05:45-18:15 -- only 11.5h before this Monday's JR01 05:45 entree.
    const priorWeekBoundaryContext: PriorDayShiftMap = new Map([["e1", { shift_start: "05:45", shift_end: "18:15" }]]);

    const { repaired, dropped } = enforceRestInvariantAcrossWeek(days, generatedShiftsByDay, 15, TEST_WEEK_START, priorWeekBoundaryContext);

    expect(repaired.Monday).toHaveLength(0);
    expect(dropped).toHaveLength(1);
  });

  it("keeps a shift separated from the employee's last real shift by an intervening OFF day when the real elapsed rest is genuinely >= 15h", () => {
    const days = ["Monday", "Tuesday"]; // Monday: no shift (OFF); Tuesday: JR01
    const generatedShiftsByDay: Record<string, GeneratedShiftAssignment[]> = {
      Monday: [],
      Tuesday: [{ employeeId: "e1", dayOfWeek: "Tuesday", shiftCode: "JR01", coversRoles: ["Boarding"] }],
    };
    // Last real shift was the PRIOR week's Sunday, ending well over 15h before Tuesday's entree.
    const priorWeekBoundaryContext: PriorDayShiftMap = new Map([["e1", { shift_start: "05:45", shift_end: "14:45" }]]);

    const { repaired, dropped } = enforceRestInvariantAcrossWeek(days, generatedShiftsByDay, 15, TEST_WEEK_START, priorWeekBoundaryContext);

    expect(repaired.Tuesday).toHaveLength(1); // kept -- real rest is ample across the OFF day
    expect(dropped).toHaveLength(0);
  });

  it("WRAPAROUND, demand-driven employee: a Sunday -> following-Monday conflict is KEPT (not dropped) when the employee id is in generationDrivenEmployeeIds, and Stage 9 eligibility (restHoursByEmployeeDay) is NOT poisoned by the low wraparound value", () => {
    const days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
    const generatedShiftsByDay: Record<string, GeneratedShiftAssignment[]> = {
      Monday: [{ employeeId: "e1", dayOfWeek: "Monday", shiftCode: "NR01", coversRoles: ["Mesure"] }], // entree 08:00
      Tuesday: [],
      Wednesday: [],
      Thursday: [],
      Friday: [],
      Saturday: [],
      Sunday: [{ employeeId: "e1", dayOfWeek: "Sunday", shiftCode: "AP02", coversRoles: ["Mesure"] }], // sortie 23:15 -> 8h45 before Monday's 08:00, well under 15h
    };

    const { repaired, dropped, restHoursByEmployeeDay } = enforceRestInvariantAcrossWeek(
      days,
      generatedShiftsByDay,
      15,
      TEST_WEEK_START,
      new Map(),
      new Set(["e1"])
    );

    expect(repaired.Monday).toHaveLength(1); // kept, not dropped
    expect(dropped).toHaveLength(0);
    // Not poisoned to the low (8.75h) wraparound value -- Stage 9 must
    // treat this employee as eligible, since the whole point of keeping
    // the shift is that this unconfirmed assumption is NOT being enforced
    // as a hard constraint. Number.POSITIVE_INFINITY is what the main
    // walk already set (no real priorWeekBoundaryContext for Monday).
    expect(restHoursByEmployeeDay.get("e1|Monday")).toBe(Number.POSITIVE_INFINITY);
  });

  it("WRAPAROUND, fixed/cyclic employee: the SAME conflict is still hard-dropped when the employee id is NOT in generationDrivenEmployeeIds (or the parameter is omitted) -- unchanged, original behavior", () => {
    const days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
    const generatedShiftsByDay: Record<string, GeneratedShiftAssignment[]> = {
      Monday: [{ employeeId: "e1", dayOfWeek: "Monday", shiftCode: "NR01", coversRoles: ["Boarding"] }],
      Tuesday: [],
      Wednesday: [],
      Thursday: [],
      Friday: [],
      Saturday: [],
      Sunday: [{ employeeId: "e1", dayOfWeek: "Sunday", shiftCode: "AP02", coversRoles: ["Boarding"] }],
    };

    // No generationDrivenEmployeeIds passed at all -- every existing
    // caller/test that predates this parameter keeps the original
    // hard-drop behavior unchanged.
    const { repaired, dropped } = enforceRestInvariantAcrossWeek(days, generatedShiftsByDay, 15, TEST_WEEK_START);

    expect(repaired.Monday).toHaveLength(0); // still dropped
    expect(dropped).toHaveLength(1);
  });
});
