import { Employee } from "../types";
import { getShiftTimesAs, restHoursForDailyRepeatingShift, LEGACY_BASELINE_DATE } from "../shift-templates";
import { buildStaggeredOffDays } from "../roster-generation";
import { deriveTeamRotation, DemandDay, RotationInfeasibleError } from "../rotation-feasibility";
import { getCompanyRequiredAgents } from "../company-config";
import { resolveDefaultLaborRules } from "../labor-rules";
import { smallDemoCompanyOperatingDays } from "./flights";

/**
 * SMALL DEMO DATASET — workforce side.
 *
 * ~48 NAMED, STABLE employees (never regenerated by index/name-pool, the
 * same approach lib/seed-data.ts uses for its 8 protected scripted
 * employees) so the same person is recognizable by name across Monthly
 * Planning and Live Operations every time this dataset is reset. This is
 * deliberately small and hand-authored, not a scaled-down call into
 * lib/employee-generator.ts's ~200-employee generator — a hand-picked
 * roster is what makes "stable, recognizable names" and "deliberately
 * tight headcount" both true at once.
 *
 * Sized against lib/demo-small/flights.ts's real demand, not in the
 * abstract — see the per-group comments below for the arithmetic. The
 * target is a plan that is NORMALLY FEASIBLE (most requirements get a
 * valid, fully-shift-contained assignment) but with little slack: a few
 * shift-code choices deliberately leave a role under-covered or a
 * candidate only "flagged" (would need an early call-in/extension), so
 * the demo has real, honest bottlenecks to click through — never
 * engineered to guarantee 100% coverage.
 *
 * 2026-10-05 CORRECTION (Moses) — Profiling/Mesure are NOT exclusive
 * teams: `assignment: "Profiling"` / `"Mesure"` is a qualification +
 * priority-commitment marker, never a claim that the employee spends
 * their whole shift on that one task. The real planning engine already
 * supports this correctly with no special-casing:
 *   - lib/planning/workforce-pools.ts's isFlexibleGeneralPool excludes
 *     Profiling/Mesure-assigned employees from Stage 6's generic
 *     Boarding/Check-in/Gate shift-code generation (so their roster
 *     placement follows their own team's demand, not generic pressure)
 *     — but that is a Stage 6 pool-membership rule, not a duty-matching
 *     rule.
 *   - lib/planning/duty-generation.ts's dayEffectivePool (Stage 9, the
 *     actual flight-by-flight duty assignment) applies NO assignment
 *     filter at all — every active, rostered employee is in scope,
 *     Profiling/Mesure included.
 *   - lib/scoring.ts's scoreCandidates hard-exclusion gate never checks
 *     assignment === "Profiling"/"Mesure" — eligibility for a given
 *     requirement is purely skills-based (or authorization-based for
 *     company_config), and occupiedWindows protects whichever window an
 *     employee is already committed to on that day.
 * In other words: the engine already reserves a Profiling/Mesure
 * employee for their specialized window via the normal duty/window
 * machinery, and otherwise lets them be scored like any other RAM ACE
 * for Gate/Boarding/Check-in. What made this small demo dataset LOOK
 * like an exclusive-team model was narrow data, not engine behavior:
 * most Profiling/Mesure employees below previously held only
 * ["Profiling"] or ["Mesure"] as their entire skills list, leaving them
 * no real path to ordinary duties even though nothing stopped the
 * engine from using one. Corrected below by giving most Profiling/
 * Mesure employees a genuine second RAM skill (Boarding/Gate/Check-in),
 * while keeping a few single-skilled as honest "pure specialist" cases
 * (Fadwa Benjelloun in Profiling; Widad Senhaji and Houda Kabbaj in
 * Mesure) so the dataset still shows both kinds of real employee.
 */

const ALL_DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
const LABOR_RULES = resolveDefaultLaborRules();
const restBeforeShiftFor = (code: string) => restHoursForDailyRepeatingShift(code, LEGACY_BASELINE_DATE);

function buildEmployee(partial: {
  id: string;
  name: string;
  skills: string[];
  assignment: string;
  shift_code: string;
  weekly_hours: number;
  off_days: string[];
  is_duty_officer?: boolean;
  foreign_company_authorizations?: string[];
}): Omit<Employee, "weekly_shifts"> {
  const { shift_start, shift_end } = getShiftTimesAs(partial.shift_code, LEGACY_BASELINE_DATE);
  return {
    id: partial.id,
    name: partial.name,
    skills: partial.skills,
    assignment: partial.assignment,
    shift_code: partial.shift_code,
    shift_start,
    shift_end,
    rest_before_shift_hours: restBeforeShiftFor(partial.shift_code),
    weekly_hours: partial.weekly_hours,
    is_duty_officer: partial.is_duty_officer ?? false,
    off_days: partial.off_days,
    foreign_company_authorizations: partial.foreign_company_authorizations ?? [],
    active: true,
  };
}

/**
 * General T1 Pool (10) — the flexible core. Shift codes span early-morning
 * (MT01/MT03 ~05:45-15:00), midday (NR01/NR02 08:00-17:00/18:15), and
 * afternoon (AP01/AP02 13:45-22:45/23:15) base codes — the real day-to-day
 * code Stage 6 actually assigns is demand-driven (lib/planning/
 * shift-generation.ts), not fixed to whichever code is listed here. An
 * employee whose assigned shift that day doesn't fully contain a given
 * flight's duty window is correctly "flagged," not auto-assignable — see
 * flights.ts's module comment for why the flight schedule is deliberately
 * kept within a single legal shift's span rather than spread across the
 * whole clock (that earlier shape caused a cross-day REST LOCKOUT, not a
 * meaningful bottleneck — see that file's comment on AT815's departure
 * time).
 */
const GENERAL_T1_POOL = [
  { id: "small-yasmine-rafiq", name: "Yasmine Rafiq", skills: ["Check-in", "Weight Control"], shift_code: "NR01", weekly_hours: 24 },
  { id: "small-othmane-belkhayat", name: "Othmane Belkhayat", skills: ["Check-in", "Weight Control"], shift_code: "MT01", weekly_hours: 24 },
  { id: "small-salma-ouahbi", name: "Salma Ouahbi", skills: ["Boarding", "Gate"], shift_code: "AP01", weekly_hours: 24 },
  { id: "small-anas-kettani", name: "Anas Kettani", skills: ["Boarding", "Gate"], shift_code: "MT01", weekly_hours: 24 },
  { id: "small-ghita-sabir", name: "Ghita Sabir", skills: ["Gate", "Care Point", "Check-in"], shift_code: "AP02", weekly_hours: 22 },
  { id: "small-reda-haddad", name: "Reda Haddad", skills: ["Gate", "Care Point", "Check-in"], shift_code: "NR02", weekly_hours: 22 },
  { id: "small-imane-ziati", name: "Imane Ziati", skills: ["Boarding", "Gate", "Care Point", "Check-in"], shift_code: "NR02", weekly_hours: 28 },
  { id: "small-bilal-choukri", name: "Bilal Choukri", skills: ["Boarding", "Gate", "Care Point", "Check-in"], shift_code: "AP01", weekly_hours: 28 },
  { id: "small-hajar-mernissi", name: "Hajar Mernissi", skills: ["Check-in", "Weight Control"], shift_code: "NR01", weekly_hours: 20 },
  { id: "small-marouane-essaidi", name: "Marouane Essaidi", skills: ["Boarding", "Gate"], shift_code: "MT01", weekly_hours: 24 },
  // 2026-10-04 (Moses: "increase the agents count a lil bit more") -- 3
  // more General T1 Pool employees, taking the roster from 22 to 25 (the
  // top of the originally requested 20-25 range). At the time this was
  // added, Profiling/Mesure were deliberately left untouched to preserve
  // their exact-capacity bottleneck -- superseded minutes later by an
  // explicit follow-up ("add about 5 agents for each RAM teams") that DID
  // ask for Profiling/Mesure to grow too; see their own comments below for
  // that second round.
  { id: "small-soukaina-idrissi", name: "Soukaina Idrissi", skills: ["Check-in", "Weight Control"], shift_code: "MT03", weekly_hours: 24 },
  { id: "small-karim-ouazzani", name: "Karim Ouazzani", skills: ["Boarding", "Gate"], shift_code: "NR01", weekly_hours: 24 },
  { id: "small-meryem-chraibi", name: "Meryem Chraibi", skills: ["Gate", "Care Point", "Check-in"], shift_code: "AP02", weekly_hours: 22 },
  // 2026-10-04 (Moses: "add about 5 agents for each RAM teams") -- 5 more.
  { id: "small-hicham-belaidi", name: "Hicham Belaidi", skills: ["Check-in", "Weight Control"], shift_code: "MT01", weekly_hours: 24 },
  { id: "small-nisrine-alami", name: "Nisrine Alami", skills: ["Boarding", "Gate"], shift_code: "AP01", weekly_hours: 24 },
  { id: "small-yassine-berrada", name: "Yassine Berrada", skills: ["Gate", "Care Point", "Check-in"], shift_code: "NR02", weekly_hours: 22 },
  { id: "small-asmae-lamrani", name: "Asmae Lamrani", skills: ["Boarding", "Gate"], shift_code: "MT03", weekly_hours: 24 },
  { id: "small-othman-ziani", name: "Othman Ziani", skills: ["Check-in", "Weight Control"], shift_code: "NR01", weekly_hours: 24 },
];

/**
 * Profiling (7) — covers AT120/AT560 (Europe/Schengen, 1 each) and AT225
 * (UK/USA, 1) on their respective days.
 *
 * 2026-10-05 CORRECTION (Moses): `assignment: "Profiling"` is this
 * employee's SPECIALIZED QUALIFICATION + priority commitment, never a
 * full-shift-exclusive team. Outside their own Profiling duty's actual
 * time window, a Profiling-assigned employee is ordinary RAM capacity --
 * see the module-level architecture note at the top of this file for the
 * full explanation of why the real engine already supports this and what
 * was data-only about the earlier framing. Most of this team now also
 * carries a genuine second RAM skill (Boarding/Gate/Check-in) so that
 * capacity is actually reachable by duty-generation.ts and Find Agent/
 * Live Ops, not just theoretically possible; a couple (Fadwa) stay
 * single-skilled as realistic pure specialists.
 */
const PROFILING = [
  { id: "small-fadwa-benjelloun", name: "Fadwa Benjelloun", skills: ["Profiling"], shift_code: "NR02", weekly_hours: 24 },
  { id: "small-khalid-amrani", name: "Khalid Amrani", skills: ["Profiling", "Boarding"], shift_code: "AP02", weekly_hours: 24 },
  { id: "small-hind-zerouali", name: "Hind Zerouali", skills: ["Profiling", "Check-in"], shift_code: "NR01", weekly_hours: 24 },
  { id: "small-mehdi-sqalli", name: "Mehdi Sqalli", skills: ["Profiling", "Boarding"], shift_code: "MT03", weekly_hours: 24 },
  { id: "small-loubna-haitami", name: "Loubna Haitami", skills: ["Profiling", "Gate"], shift_code: "AP01", weekly_hours: 24 },
  { id: "small-adil-benomar", name: "Adil Benomar", skills: ["Profiling", "Gate"], shift_code: "NR02", weekly_hours: 24 },
  { id: "small-siham-raji", name: "Siham Raji", skills: ["Profiling", "Check-in"], shift_code: "MT01", weekly_hours: 24 },
];

/**
 * Mesure (9) — AT225 (Mon/Wed/Fri only) needs exactly 4 Mesure agents at
 * once (the confirmed flat Mesure headcount, lib/ram-staffing-matrix.ts).
 *
 * 2026-10-05 CORRECTION (Moses): same correction as Profiling above --
 * `assignment: "Mesure"` is a qualification + priority reservation for
 * AT225's Mesure window, not an exclusive full-shift team. Before this
 * correction every Mesure employee here was single-skilled (["Mesure"]
 * only), which meant NONE of them could ever pick up ordinary Gate/
 * Boarding/Check-in work during their real idle time -- an accurate
 * description of the data, but not of the intended RAM workforce model,
 * and not a limitation of the actual scoring/duty-generation engine (see
 * this file's top-of-module note). Most of this team now also carries a
 * genuine second RAM skill so duty-generation.ts and Find Agent/Live Ops
 * can actually offer them for Boarding/Gate/Check-in outside their
 * protected Mesure window; two (Widad, Houda) stay single-skilled as
 * realistic pure specialists.
 */
const MESURE = [
  { id: "small-widad-senhaji", name: "Widad Senhaji", skills: ["Mesure"], shift_code: "MT02", weekly_hours: 28 },
  { id: "small-tarik-bouhafa", name: "Tarik Bouhafa", skills: ["Mesure", "Boarding"], shift_code: "MT02", weekly_hours: 28 },
  { id: "small-houda-kabbaj", name: "Houda Kabbaj", skills: ["Mesure"], shift_code: "NR01", weekly_hours: 24 },
  { id: "small-samir-tazi", name: "Samir Tazi", skills: ["Mesure", "Gate"], shift_code: "NR01", weekly_hours: 24 },
  { id: "small-nadia-berrada", name: "Nadia Berrada", skills: ["Mesure", "Check-in"], shift_code: "MT02", weekly_hours: 24 },
  { id: "small-youssef-idrissi", name: "Youssef Idrissi", skills: ["Mesure", "Boarding"], shift_code: "NR02", weekly_hours: 24 },
  { id: "small-ikram-fehri", name: "Ikram Fehri", skills: ["Mesure", "Gate"], shift_code: "MT01", weekly_hours: 24 },
  { id: "small-rachid-ammor", name: "Rachid Ammor", skills: ["Mesure", "Check-in"], shift_code: "AP01", weekly_hours: 24 },
  { id: "small-dounia-sabban", name: "Dounia Sabban", skills: ["Mesure", "Profiling"], shift_code: "NR01", weekly_hours: 24 },
];

/** Builds the flat-rule (non-fixed-cycle, non-foreign) employees above, each staggered 2 OFF days/week, Wednesday kept working (matches the main dataset's convention for any skill a live requirement queries directly). */
function buildFlatRuleEmployees(
  specs: { id: string; name: string; skills: string[]; shift_code: string; weekly_hours: number }[],
  assignment: string
): Omit<Employee, "weekly_shifts">[] {
  const candidatePool = ALL_DAYS.filter((d) => d !== "Wednesday");
  return specs.map((spec, n) =>
    buildEmployee({
      ...spec,
      assignment,
      off_days: buildStaggeredOffDays(n, LABOR_RULES.normalWeeklyOffDays, candidatePool),
    })
  );
}

/**
 * Generic foreign-company group builder (2026-10-04 — extracted from what
 * was a Qatar-Airways-only `buildQatarAirwaysGroup`, per Moses: "add
 * foreign companies teams"). Headcount derived through the SAME generic
 * Rotation Feasibility Engine the main dataset's foreign-company groups
 * use (lib/rotation-feasibility.ts), off the company's REAL flight days
 * (smallDemoCompanyOperatingDays) — never hand-picked off-days, and never
 * a silently-invented fallback if infeasible (throws
 * RotationInfeasibleError, exactly like lib/employee-generator.ts). Every
 * company using this stays on the same "Boarding" nominal skill — see
 * company-config.ts's own doc comment: eligibility for a company_config
 * requirement is never a skill match, only the real
 * foreign_company_authorizations for that specific airline, so the skill
 * value here carries no scoring weight at all.
 */
function buildForeignCompanyGroup(
  assignment: string,
  names: { id: string; name: string }[],
  shiftCode: string,
  weeklyHours: number
): Omit<Employee, "weekly_shifts">[] {
  const flightDays = smallDemoCompanyOperatingDays(assignment);
  const requiredAgents = getCompanyRequiredAgents(assignment);
  if (requiredAgents === undefined) {
    throw new Error(`"${assignment}" has no confirmed company_config headcount — lib/company-config.ts must define it before the small demo can roster this group.`);
  }
  const demand: DemandDay[] = ALL_DAYS.map((d) => ({ dayOfWeek: d, requiredAgents: flightDays.includes(d) ? requiredAgents : 0 }));

  const count = names.length;
  const result = deriveTeamRotation(count, demand, ALL_DAYS, LABOR_RULES.normalWeeklyOffDays, undefined, 4, LABOR_RULES.maxConsecutiveOffDays);
  if (!result.feasible || !result.candidate) {
    throw new RotationInfeasibleError(assignment, count, demand, result.reason ?? "No feasible rotation found.", LABOR_RULES.normalWeeklyOffDays);
  }

  const offDaysByMember: string[][] = [];
  for (const group of result.candidate.groups) {
    for (let k = 0; k < group.size; k++) offDaysByMember.push(group.offDays);
  }

  return names.map((n, i) =>
    buildEmployee({
      id: n.id,
      name: n.name,
      skills: ["Boarding"],
      assignment,
      shift_code: shiftCode,
      weekly_hours: weeklyHours,
      off_days: offDaysByMember[i],
      foreign_company_authorizations: [assignment],
    })
  );
}

/** Qatar Airways (3) — real demand: 2 agents/flight, Mon/Wed/Fri only. */
const QATAR_AIRWAYS_NAMES = [
  { id: "small-nawal-fassi", name: "Nawal Fassi" },
  { id: "small-yassine-rifai", name: "Yassine Rifai" },
  { id: "small-btissam-guessous", name: "Btissam Guessous" },
];

/**
 * Emirates (4) — real demand: 3 agents/flight, Tue/Thu/Sat/Sun (see
 * flights.ts's EK702). One more member than the per-flight headcount, so
 * the rotation has enough slack to actually produce a legal weekly-off
 * schedule across 4 operating days/week (3-for-3 with zero spare, like
 * Qatar's 3-for-2, would otherwise have nobody able to take a protected
 * OFF day without leaving the flight short).
 */
const EMIRATES_NAMES = [
  { id: "small-hamza-benchekroun", name: "Hamza Benchekroun" },
  { id: "small-rania-berrada", name: "Rania Berrada" },
  { id: "small-omar-lahrichi", name: "Omar Lahrichi" },
  { id: "small-sara-mejjati", name: "Sara Mejjati" },
];

/** Air France (4) — real demand: 3 agents/flight, Mon/Wed/Fri (see flights.ts's AF1680). Same slack reasoning as Emirates above. */
const AIR_FRANCE_NAMES = [
  { id: "small-yassmina-touzani", name: "Yassmina Touzani" },
  { id: "small-amine-zniber", name: "Amine Zniber" },
  { id: "small-khadija-sefrioui", name: "Khadija Sefrioui" },
  { id: "small-walid-ennaciri", name: "Walid Ennaciri" },
];

/**
 * One Duty Officer and one Transit agent — small (1 each), purely to keep
 * both FIXED_PLANNING_TEAMS exclusions (lib/teams.ts) exercisable in the
 * UI (never offered as ordinary candidates) without allocating headcount
 * this dataset's actual flight demand doesn't call for. Both use the same
 * confirmed JR->NT->OFF->OFF cycle as the main dataset
 * (lib/fixed-cycle-rotation.ts).
 */
import { JR_NT_OFF_OFF_CYCLE, buildFixedCycleWeeklySchedule, offDaysForDisplayedWeek, FixedCycleDefinition } from "../fixed-cycle-rotation";

export interface SmallDemoFixedCycleSeed {
  employee: Omit<Employee, "weekly_shifts">;
  cycle: FixedCycleDefinition;
  cycleOffset: number;
}

function buildFixedCycleEmployee(id: string, name: string, skills: string[], assignment: string, cycleOffset: number): SmallDemoFixedCycleSeed {
  const cycle = JR_NT_OFF_OFF_CYCLE;
  const off_days = offDaysForDisplayedWeek(cycle, cycleOffset, ALL_DAYS);
  const referenceStep = cycle.steps.find((s) => "code" in s) as { code: string } | undefined;
  const referenceCode = referenceStep?.code ?? null;
  const { shift_start, shift_end } = referenceCode ? getShiftTimesAs(referenceCode, LEGACY_BASELINE_DATE) : { shift_start: null, shift_end: null };
  return {
    employee: {
      id,
      name,
      skills,
      assignment,
      shift_code: referenceCode,
      shift_start,
      shift_end,
      rest_before_shift_hours: referenceCode ? restBeforeShiftFor(referenceCode) : 0,
      weekly_hours: 30,
      is_duty_officer: assignment === "Duty Officers",
      off_days,
      foreign_company_authorizations: [],
      active: true,
    },
    cycle,
    cycleOffset,
  };
}

export const SMALL_DEMO_FIXED_CYCLE_EMPLOYEES: SmallDemoFixedCycleSeed[] = [
  buildFixedCycleEmployee("small-nabil-cherkaoui", "Nabil Cherkaoui", ["Boarding"], "Duty Officers", 0),
  buildFixedCycleEmployee("small-aziz-lahlou", "Aziz Lahlou", ["Transit"], "Transit", 2),
];

/**
 * A rotating-shift example (1) — same demonstrative purpose as the main
 * dataset's Amine Sqalli: concrete, non-uniform day-to-day shift-code
 * variety (MT01 most days, AP01 Saturday) for one General T1 Pool
 * employee, with the confirmed flat 2-OFF-days rule (Thursday, Sunday).
 */
const ROTATING_PATTERN: { day: string; code: string | null }[] = [
  { day: "Monday", code: "MT01" },
  { day: "Tuesday", code: "MT01" },
  { day: "Wednesday", code: "MT01" },
  { day: "Thursday", code: "OFF" },
  { day: "Friday", code: "MT01" },
  { day: "Saturday", code: "AP01" },
  { day: "Sunday", code: "OFF" },
];

function buildRotatingEmployee(): { employee: Omit<Employee, "weekly_shifts">; pattern: typeof ROTATING_PATTERN } {
  return {
    employee: buildEmployee({
      id: "small-mounir-skalli",
      name: "Mounir Skalli",
      skills: ["Gate"],
      assignment: "General T1 Pool",
      shift_code: "MT01",
      weekly_hours: 24,
      off_days: ["Thursday", "Sunday"],
    }),
    pattern: ROTATING_PATTERN,
  };
}

export const SMALL_DEMO_ROTATING_EMPLOYEE = buildRotatingEmployee();

/**
 * Flat-rule employees (General T1 Pool + Profiling + Mesure) — built once
 * here so dataset.ts can assemble weekly_shifts for all of them
 * identically (buildUniformWeeklySchedule), same as the main dataset's
 * generated pool.
 */
export const SMALL_DEMO_FLAT_RULE_EMPLOYEES: Omit<Employee, "weekly_shifts">[] = [
  ...buildFlatRuleEmployees(GENERAL_T1_POOL, "General T1 Pool"),
  ...buildFlatRuleEmployees(PROFILING, "Profiling"),
  ...buildFlatRuleEmployees(MESURE, "Mesure"),
];

export const SMALL_DEMO_QATAR_AIRWAYS_EMPLOYEES: Omit<Employee, "weekly_shifts">[] = buildForeignCompanyGroup(
  "Qatar Airways",
  QATAR_AIRWAYS_NAMES,
  "NR01",
  24
);
export const SMALL_DEMO_EMIRATES_EMPLOYEES: Omit<Employee, "weekly_shifts">[] = buildForeignCompanyGroup(
  "Emirates",
  EMIRATES_NAMES,
  "NR02",
  24
);
export const SMALL_DEMO_AIR_FRANCE_EMPLOYEES: Omit<Employee, "weekly_shifts">[] = buildForeignCompanyGroup(
  "Air France",
  AIR_FRANCE_NAMES,
  "AP01",
  24
);

// 18 General T1 Pool + 7 Profiling + 9 Mesure + 3 Qatar Airways + 4
// Emirates + 4 Air France + 1 Duty Officer + 1 Transit + 1 rotating-shift
// example = 48 employees total.
export const SMALL_DEMO_EMPLOYEE_COUNT =
  SMALL_DEMO_FLAT_RULE_EMPLOYEES.length +
  SMALL_DEMO_QATAR_AIRWAYS_EMPLOYEES.length +
  SMALL_DEMO_EMIRATES_EMPLOYEES.length +
  SMALL_DEMO_AIR_FRANCE_EMPLOYEES.length +
  SMALL_DEMO_FIXED_CYCLE_EMPLOYEES.length +
  1;
