import { Employee } from "../types";
import { getShiftTimesAs, restHoursForDailyRepeatingShift, LEGACY_BASELINE_DATE } from "../shift-templates";
import { buildStaggeredOffDays } from "../roster-generation";
import { deriveTeamRotation, DemandDay, RotationInfeasibleError } from "../rotation-feasibility";
import { getCompanyRequiredAgents } from "../company-config";
import { resolveDefaultLaborRules } from "../labor-rules";
import { smallDemoCompanyOperatingDays } from "./flights";

/**
 * SMALL DEMO DATASET — workforce side.
 *
 * ~22 NAMED, STABLE employees (never regenerated by index/name-pool, the
 * same approach lib/seed-data.ts uses for its 8 protected scripted
 * employees) so the same person is recognizable by name across Monthly
 * Planning and Live Operations every time this dataset is reset. This is
 * deliberately small and hand-authored, not a scaled-down call into
 * lib/employee-generator.ts's ~200-employee generator — a hand-picked
 * roster is what makes "stable, recognizable names" and "deliberately
 * tight headcount" both true at once.
 *
 * Sized against lib/demo-small/flights.ts's real demand, not in the
 * abstract — see the per-group comments below for the arithmetic. The
 * target is a plan that is NORMALLY FEASIBLE (most requirements get a
 * valid, fully-shift-contained assignment) but with little slack: a few
 * shift-code choices deliberately leave a role under-covered or a
 * candidate only "flagged" (would need an early call-in/extension), so
 * the demo has real, honest bottlenecks to click through — never
 * engineered to guarantee 100% coverage.
 */

const ALL_DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
const LABOR_RULES = resolveDefaultLaborRules();
const restBeforeShiftFor = (code: string) => restHoursForDailyRepeatingShift(code, LEGACY_BASELINE_DATE);

function buildEmployee(partial: {
  id: string;
  name: string;
  skills: string[];
  assignment: string;
  shift_code: string;
  weekly_hours: number;
  off_days: string[];
  is_duty_officer?: boolean;
  foreign_company_authorizations?: string[];
}): Omit<Employee, "weekly_shifts"> {
  const { shift_start, shift_end } = getShiftTimesAs(partial.shift_code, LEGACY_BASELINE_DATE);
  return {
    id: partial.id,
    name: partial.name,
    skills: partial.skills,
    assignment: partial.assignment,
    shift_code: partial.shift_code,
    shift_start,
    shift_end,
    rest_before_shift_hours: restBeforeShiftFor(partial.shift_code),
    weekly_hours: partial.weekly_hours,
    is_duty_officer: partial.is_duty_officer ?? false,
    off_days: partial.off_days,
    foreign_company_authorizations: partial.foreign_company_authorizations ?? [],
    active: true,
  };
}

/**
 * General T1 Pool (10) — the flexible core. Shift codes span early-morning
 * (MT01/MT03 ~05:45-15:00), midday (NR01/NR02 08:00-17:00/18:15), and
 * afternoon (AP01/AP02 13:45-22:45/23:15) base codes — the real day-to-day
 * code Stage 6 actually assigns is demand-driven (lib/planning/
 * shift-generation.ts), not fixed to whichever code is listed here. An
 * employee whose assigned shift that day doesn't fully contain a given
 * flight's duty window is correctly "flagged," not auto-assignable — see
 * flights.ts's module comment for why the flight schedule is deliberately
 * kept within a single legal shift's span rather than spread across the
 * whole clock (that earlier shape caused a cross-day REST LOCKOUT, not a
 * meaningful bottleneck — see that file's comment on AT815's departure
 * time).
 */
const GENERAL_T1_POOL = [
  { id: "small-yasmine-rafiq", name: "Yasmine Rafiq", skills: ["Check-in", "Weight Control"], shift_code: "NR01", weekly_hours: 24 },
  { id: "small-othmane-belkhayat", name: "Othmane Belkhayat", skills: ["Check-in", "Weight Control"], shift_code: "MT01", weekly_hours: 24 },
  { id: "small-salma-ouahbi", name: "Salma Ouahbi", skills: ["Boarding", "Gate"], shift_code: "AP01", weekly_hours: 24 },
  { id: "small-anas-kettani", name: "Anas Kettani", skills: ["Boarding", "Gate"], shift_code: "MT01", weekly_hours: 24 },
  { id: "small-ghita-sabir", name: "Ghita Sabir", skills: ["Gate", "Care Point", "Check-in"], shift_code: "AP02", weekly_hours: 22 },
  { id: "small-reda-haddad", name: "Reda Haddad", skills: ["Gate", "Care Point", "Check-in"], shift_code: "NR02", weekly_hours: 22 },
  { id: "small-imane-ziati", name: "Imane Ziati", skills: ["Boarding", "Gate", "Care Point", "Check-in"], shift_code: "NR02", weekly_hours: 28 },
  { id: "small-bilal-choukri", name: "Bilal Choukri", skills: ["Boarding", "Gate", "Care Point", "Check-in"], shift_code: "AP01", weekly_hours: 28 },
  { id: "small-hajar-mernissi", name: "Hajar Mernissi", skills: ["Check-in", "Weight Control"], shift_code: "NR01", weekly_hours: 20 },
  { id: "small-marouane-essaidi", name: "Marouane Essaidi", skills: ["Boarding", "Gate"], shift_code: "MT01", weekly_hours: 24 },
];

/**
 * Profiling (2) — covers AT120/AT560 (Europe/Schengen, 1 each) and AT225
 * (UK/USA, 1) on their respective days. 2 people for up to 3 simultaneous
 * daily Profiling slots (Mon/Wed/Fri: AT120+AT560+AT225) is intentionally
 * tight — one of the three will routinely go uncovered or need a
 * flagged/manual pick, a real bottleneck, not a gap to paper over.
 */
const PROFILING = [
  { id: "small-fadwa-benjelloun", name: "Fadwa Benjelloun", skills: ["Profiling"], shift_code: "NR02", weekly_hours: 24 },
  { id: "small-khalid-amrani", name: "Khalid Amrani", skills: ["Profiling", "Boarding"], shift_code: "AP02", weekly_hours: 24 },
];

/**
 * Mesure (4) — AT225 (Mon/Wed/Fri only) needs exactly 4 Mesure agents at
 * once (the confirmed flat Mesure headcount, lib/ram-staffing-matrix.ts).
 * 4 dedicated Mesure employees is therefore the minimum that can ever
 * fully cover it — zero spare capacity: any OFF day, rest shortfall, or
 * shift mismatch among these 4 on a Mon/Wed/Fri directly produces an
 * uncovered Mesure slot. This is deliberate: Mesure is the dataset's
 * sharpest, most predictable bottleneck.
 */
const MESURE = [
  { id: "small-widad-senhaji", name: "Widad Senhaji", skills: ["Mesure"], shift_code: "MT02", weekly_hours: 28 },
  { id: "small-tarik-bouhafa", name: "Tarik Bouhafa", skills: ["Mesure", "Profiling"], shift_code: "MT02", weekly_hours: 28 },
  { id: "small-houda-kabbaj", name: "Houda Kabbaj", skills: ["Mesure"], shift_code: "NR01", weekly_hours: 24 },
  { id: "small-samir-tazi", name: "Samir Tazi", skills: ["Mesure"], shift_code: "NR01", weekly_hours: 24 },
];

/** Builds the 16 flat-rule (non-fixed-cycle, non-foreign) employees above, each staggered 2 OFF days/week, Wednesday kept working (matches the main dataset's convention for any skill a live requirement queries directly). */
function buildFlatRuleEmployees(
  specs: { id: string; name: string; skills: string[]; shift_code: string; weekly_hours: number }[],
  assignment: string
): Omit<Employee, "weekly_shifts">[] {
  const candidatePool = ALL_DAYS.filter((d) => d !== "Wednesday");
  return specs.map((spec, n) =>
    buildEmployee({
      ...spec,
      assignment,
      off_days: buildStaggeredOffDays(n, LABOR_RULES.normalWeeklyOffDays, candidatePool),
    })
  );
}

/**
 * Qatar Airways (3) — the small demo's one foreign-company group. Real
 * demand: 2 agents/flight, Mon/Wed/Fri only (see flights.ts). Headcount
 * derived through the SAME generic Rotation Feasibility Engine the main
 * dataset's foreign-company groups use (lib/rotation-feasibility.ts), off
 * their REAL flight days here — never hand-picked off-days, and never a
 * silently-invented fallback if infeasible (throws RotationInfeasibleError,
 * exactly like lib/employee-generator.ts).
 */
function buildQatarAirwaysGroup(): Omit<Employee, "weekly_shifts">[] {
  const assignment = "Qatar Airways";
  const flightDays = smallDemoCompanyOperatingDays(assignment);
  const requiredAgents = getCompanyRequiredAgents(assignment);
  if (requiredAgents === undefined) {
    throw new Error(`"${assignment}" has no confirmed company_config headcount — lib/company-config.ts must define it before the small demo can roster this group.`);
  }
  const demand: DemandDay[] = ALL_DAYS.map((d) => ({ dayOfWeek: d, requiredAgents: flightDays.includes(d) ? requiredAgents : 0 }));

  const count = 3;
  const result = deriveTeamRotation(count, demand, ALL_DAYS, LABOR_RULES.normalWeeklyOffDays, undefined, 4, LABOR_RULES.maxConsecutiveOffDays);
  if (!result.feasible || !result.candidate) {
    throw new RotationInfeasibleError(assignment, count, demand, result.reason ?? "No feasible rotation found.", LABOR_RULES.normalWeeklyOffDays);
  }

  const offDaysByMember: string[][] = [];
  for (const group of result.candidate.groups) {
    for (let k = 0; k < group.size; k++) offDaysByMember.push(group.offDays);
  }

  const names = [
    { id: "small-nawal-fassi", name: "Nawal Fassi" },
    { id: "small-yassine-rifai", name: "Yassine Rifai" },
    { id: "small-btissam-guessous", name: "Btissam Guessous" },
  ];

  return names.map((n, i) =>
    buildEmployee({
      id: n.id,
      name: n.name,
      skills: ["Boarding"],
      assignment,
      shift_code: "NR01",
      weekly_hours: 24,
      off_days: offDaysByMember[i],
      foreign_company_authorizations: [assignment],
    })
  );
}

/**
 * One Duty Officer and one Transit agent — small (1 each), purely to keep
 * both FIXED_PLANNING_TEAMS exclusions (lib/teams.ts) exercisable in the
 * UI (never offered as ordinary candidates) without allocating headcount
 * this dataset's actual flight demand doesn't call for. Both use the same
 * confirmed JR->NT->OFF->OFF cycle as the main dataset
 * (lib/fixed-cycle-rotation.ts).
 */
import { JR_NT_OFF_OFF_CYCLE, buildFixedCycleWeeklySchedule, offDaysForDisplayedWeek, FixedCycleDefinition } from "../fixed-cycle-rotation";

export interface SmallDemoFixedCycleSeed {
  employee: Omit<Employee, "weekly_shifts">;
  cycle: FixedCycleDefinition;
  cycleOffset: number;
}

function buildFixedCycleEmployee(id: string, name: string, skills: string[], assignment: string, cycleOffset: number): SmallDemoFixedCycleSeed {
  const cycle = JR_NT_OFF_OFF_CYCLE;
  const off_days = offDaysForDisplayedWeek(cycle, cycleOffset, ALL_DAYS);
  const referenceStep = cycle.steps.find((s) => "code" in s) as { code: string } | undefined;
  const referenceCode = referenceStep?.code ?? null;
  const { shift_start, shift_end } = referenceCode ? getShiftTimesAs(referenceCode, LEGACY_BASELINE_DATE) : { shift_start: null, shift_end: null };
  return {
    employee: {
      id,
      name,
      skills,
      assignment,
      shift_code: referenceCode,
      shift_start,
      shift_end,
      rest_before_shift_hours: referenceCode ? restBeforeShiftFor(referenceCode) : 0,
      weekly_hours: 30,
      is_duty_officer: assignment === "Duty Officers",
      off_days,
      foreign_company_authorizations: [],
      active: true,
    },
    cycle,
    cycleOffset,
  };
}

export const SMALL_DEMO_FIXED_CYCLE_EMPLOYEES: SmallDemoFixedCycleSeed[] = [
  buildFixedCycleEmployee("small-nabil-cherkaoui", "Nabil Cherkaoui", ["Boarding"], "Duty Officers", 0),
  buildFixedCycleEmployee("small-aziz-lahlou", "Aziz Lahlou", ["Transit"], "Transit", 2),
];

/**
 * A rotating-shift example (1) — same demonstrative purpose as the main
 * dataset's Amine Sqalli: concrete, non-uniform day-to-day shift-code
 * variety (MT01 most days, AP01 Saturday) for one General T1 Pool
 * employee, with the confirmed flat 2-OFF-days rule (Thursday, Sunday).
 */
const ROTATING_PATTERN: { day: string; code: string | null }[] = [
  { day: "Monday", code: "MT01" },
  { day: "Tuesday", code: "MT01" },
  { day: "Wednesday", code: "MT01" },
  { day: "Thursday", code: "OFF" },
  { day: "Friday", code: "MT01" },
  { day: "Saturday", code: "AP01" },
  { day: "Sunday", code: "OFF" },
];

function buildRotatingEmployee(): { employee: Omit<Employee, "weekly_shifts">; pattern: typeof ROTATING_PATTERN } {
  return {
    employee: buildEmployee({
      id: "small-mounir-skalli",
      name: "Mounir Skalli",
      skills: ["Gate"],
      assignment: "General T1 Pool",
      shift_code: "MT01",
      weekly_hours: 24,
      off_days: ["Thursday", "Sunday"],
    }),
    pattern: ROTATING_PATTERN,
  };
}

export const SMALL_DEMO_ROTATING_EMPLOYEE = buildRotatingEmployee();

/**
 * Flat-rule employees (General T1 Pool + Profiling + Mesure) — 16 total,
 * built once here so dataset.ts can assemble weekly_shifts for all of
 * them identically (buildUniformWeeklySchedule), same as the main
 * dataset's generated pool.
 */
export const SMALL_DEMO_FLAT_RULE_EMPLOYEES: Omit<Employee, "weekly_shifts">[] = [
  ...buildFlatRuleEmployees(GENERAL_T1_POOL, "General T1 Pool"),
  ...buildFlatRuleEmployees(PROFILING, "Profiling"),
  ...buildFlatRuleEmployees(MESURE, "Mesure"),
];

export const SMALL_DEMO_QATAR_AIRWAYS_EMPLOYEES: Omit<Employee, "weekly_shifts">[] = buildQatarAirwaysGroup();

// 10 General T1 Pool + 2 Profiling + 4 Mesure + 3 Qatar Airways + 1 Duty
// Officer + 1 Transit + 1 rotating-shift example = 22 employees total.
export const SMALL_DEMO_EMPLOYEE_COUNT =
  SMALL_DEMO_FLAT_RULE_EMPLOYEES.length + SMALL_DEMO_QATAR_AIRWAYS_EMPLOYEES.length + SMALL_DEMO_FIXED_CYCLE_EMPLOYEES.length + 1;
